### PR TITLE
Pull request Face toolbox from other repo 

### PR DESCRIPTION
**Pull request by nils-tekampe**
This is the equivalent pull request for https://github.com/biometricITC/cPP-biometrics/pull/156#issuecomment-474330211 containing the contribtution from @stemotre

### CODE REVIEW

**Comment by stemotre** [comment]
Thank you for moving and converting.
I do not understand what is the 2D-Face toolbox in the folder.

**Comment by woodbe** [comment]
It is the older "original" toolbox example from @n-kai. Since we weren't sure exactly what you would create, I had kept them separate, but if yours covers 2D and 3D, then we will probably want to see if there is anything to add from the original, but otherwise we may just list the 3D as the one to use.

**Comment by nils-tekampe** [comment]
@stemotre If you delete this old folder in your face-toolbox-branch it will get removed at the same time that your new contribution will be added. You just need to ensure that you cover the content

**Comment by stemotre** [comment]
Ok, thank you for the history..
So I would merge both into a single Face toolbox. The argument being that there is no such thing as a 2D person's face. The inputs can be 2D or 3D, the goal of the toolbox is to be able to distinguish the person trying to authenticate from the enrolled person. The technology can be 2D based, but it should not mean that 3D tests are discarded.
Does it make sense?

**Comment by nils-tekampe** [comment]
Sounds good for me (but I have to admit that I did not read your contribution yet)

**Comment by nils-tekampe** [comment]
I created another pull request to cover this content and just merged it into develop as discussed yesterday. So, this PR can be closed.

**Pull request closed without merging**
