### PR TITLE
two editorial fixes (#40)

### LINKED ISSUE #22: Section 2.1 confusion
Are 3 test subjects used for the creation of 1 Presentation Attack Instrument? I think the wording of the first sentence of section 2.1 in toolbox.adoc could be clarified.

### LINKED ISSUE #23: Section 2.4 Testing
If the TOE matches the previously enrolled user, the test fails? Is this artefact from a different user that hasn't been enrolled by the TOE? I don't think the bullet is clear in Section 2.4 of toolbox.adoc.

### PR DESCRIPTION
**Pull request by woodbe**
* two editorial fixes

Fix the errors in table

### CODE REVIEW

**Comment by woodbe** [comment]
This looks like a lot of changes due to how the PR was created, but is actually just 2 editorial changes.

**Comment by BrJu** [comment]
Shouldn't you keep *Variations* into the 2nd modification?

**Comment by n-kai** [comment]
@BrJu 
Nice to hear from you again, you are right. I don't know why Variations is disappeared but it should be there.
@woodb
I created PR #42

**Comment by woodb** [comment]
> @BrJu
> Nice to hear from you again, you are right. I don't know why Variations is disappeared but it should be there.
> @woodb
> I created PR #42

I think you meant @woodbe 😛

**Comment by woodbe** [comment]
This has been approved by the iTC membership (results with email addresses removed).
[Ballot for Technical Recommendation BIO0001 (Responses).xlsx](https://github.com/biometricITC/cPP-toolboxes/files/4987644/Ballot.for.Technical.Recommendation.BIO0001.Responses.xlsx)

**Pull request merged**
