### PR TITLE
lifespan

### LINKED ISSUE #54: Artefact Lifespan
Fingerprint Toolbox Overview Section: 4.2.3 Cast (PAI) preparation - In this section we are given lifespans for fingerprint molds and casts depending on the type of material. A similar list is not given for other PAIs in other toolboxes. For example, how long is a 3D printed face mask usable for? Will three need to be created for each of the three test subjects for each new evaluation? Proposing that an artefact remain usable indefinitely for testing if it has been stored to manufacturer’s recommendations and remains free of visible defects.

### PR DESCRIPTION
**Pull request by woodbe**
Added some text about the lifespan of artefacts, mainly to state that they can be stored according to manufacturer's recommendations to be re-used, but that this must be documented.

This is to close #54

### CODE REVIEW

**Comment by gregott** [comment]
I think we would want the PAI to be be a reasonable representation of the enrolled biometric.  From an attacker perspective it may not be feasible to separate the presentation used for PAD processing from the presentation used for matching.  So an attacker would likely want his PAI to serve both the matching and PAD attacks.  This may drive some requirements on the vendor to provide to the labs evaluation versions of their PAD approach to separate the PAD and matching processing so the lab can distinguish between failing/passing PAD from failing/passing biometric matching.

**Comment by woodbe** [comment]
@gregott on looking more at your question and the document, I'm not sure we have any real way to do that. I don't know that the devices will be able to provide that type of split usage (at least not easily), to be able to verify by device check that the artefact matches the person's fingerprint. I think that the visual check (for things like cuts, etc) may be as far as we can go at this point.

**Comment by gregott** [comment]
Not being able to separate the PAD and matching processing makes it impossible to know why the presentation was rejected.  How would the lab know if an artefact passed PAD but did not match the biometric vs the other way around if the TOE does not inform the tester. Clearly we do not want the user to ever know why his presentation failed.  If the lab does not know how will they be able to calculate error rates?

**Comment by woodbe** [comment]
Add IAPAR definition to section 7.1 in BIOSD and reference FIDO/ISO as source

Add IAPAR definition/link to IAPAR in section 1 of Toolbox (also fix reference in second paragraph that points to section 6 in BIOSD which should be 7)

**Comment by gregott** [comment]
Adding IAPAR is good.

Here are my thoughts on PAI storage.

Not all changes that occur during storage which impact PAD performance may be visible to the human eye.  For example, if a conductive coating on a fingerprint PAI becomes less conductive over time, that change may not manifest in a visible change to the artefact.  Further, PAIs may be combining “ingredients” in a way not covered by manufacturer recommendations.  It may not be clear how to properly store a PAI and for how long. 

I would suggest that the lab be required to produce a minimum number (percentage) of fresh PAIs for each PAI species used in an evaluation.  If the performance of the stored PAIs is found to be significantly lower than the performance of the fresh ones, then the stored PAIs should be discarded along with their test results and replaced with fresh PAIs for that evaluation.  I am open to suggestions regarding how many / what percentage is best as well as how to bound the performance of each set of PAIs to determine if the old ones should be discarded. 

We may find over time that certain stored PAIs consistently perform as well as fresh ones, for example a printed photograph.  At some point we may update the above guidance to exclude these PAIs.

**Comment by woodbe** [comment]
@gregott I like the idea of having a mix of new and stored artefacts being used, but what I'm thinking is that the mix may be dependent on the modality. For example, the flat pictures we know should be good (as would be digital images) for long term, and likely 3D printed masks are likely to be good (though that depends on the materials, obviously). So I could be good with say using new artefacts for 2 out of 10 users there, but may want 4 out of 10 for fingerprint. And fingerprint also has the question of how long a mold is good for (likely longer than the artefact, but technically both have a lifetime).

I have put this into the document at the end, and will update the overviews to have a section with some proposed numbers for each modality.

**Review by n-kai — CHANGES_REQUESTED** [review]
I created #60 to introduce some changes to this PR.

**Comment by woodbe** [comment]
Merged based on agreement on 7/26 call

**Pull request merged**
